# Generated by Django 4.1.5 on 2023-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
