# Generated by Django 4.1.5 on 2023-02-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_options_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='linkedln',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
