# Generated by Django 4.1.5 on 2023-02-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_advertisement_id_alter_blog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
