# Generated by Django 4.1.5 on 2023-02-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_news_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
