# Generated by Django 4.1.5 on 2023-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_us',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image1',
            field=models.ImageField(default=' ', upload_to='media/image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image2',
            field=models.ImageField(default=1, upload_to='media/image2'),
            preserve_default=False,
        ),
    ]
