# Generated by Django 4.1.5 on 2023-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings_about_us_settings_image1_settings_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='information1',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='information2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
