# Generated by Django 4.1.5 on 2023-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings_description1_settings_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='button',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
