# Generated by Django 4.1.5 on 2023-02-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_settings_button'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
