# Generated by Django 4.1.5 on 2023-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_az',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
