# Generated by Django 4.1.5 on 2023-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_description_az_news_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
