# Generated by Django 4.1.5 on 2023-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=' ', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
