# Generated by Django 4.1.5 on 2023-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_options_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=' ', upload_to='media/homepage2'),
            preserve_default=False,
        ),
    ]
