# Generated by Django 4.1.5 on 2023-02-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_image_products_image1_products_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
    ]
