# Generated by Django 4.1.5 on 2023-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_az',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
