# Generated by Django 4.1.5 on 2023-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='compared_price',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
